/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx}',
    './components/**/*.{js,jsx}',
  ],
  theme: {
    extend: {
      colors: {
        "error": "#ba1a1a",
        "inverse-on-surface": "#f1efff",
        "secondary-fixed": "#ffdbcc",
        "surface-tint": "#5b5d74",
        "surface-variant": "#e0e0fc",
        "surface-container-high": "#e6e6ff",
        "on-secondary-fixed-variant": "#7b2f00",
        "tertiary": "#0e1a2a",
        "on-tertiary-fixed-variant": "#3c475a",
        "inverse-surface": "#2d2f44",
        "secondary-container": "#fd711f",
        "background": "#fbf8ff",
        "primary-fixed-dim": "#c4c4df",
        "on-surface": "#181a2e",
        "outline-variant": "#c7c5cd",
        "outline": "#77767d",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#d7e3fa",
        "on-tertiary-fixed": "#101c2c",
        "tertiary-fixed-dim": "#bbc7dd",
        "secondary-fixed-dim": "#ffb694",
        "tertiary-container": "#232f40",
        "on-tertiary-container": "#8b97ab",
        "primary-fixed": "#e0e0fc",
        "surface-container-highest": "#e0e0fc",
        "on-error-container": "#93000a",
        "primary-container": "#2b2d42",
        "on-error": "#ffffff",
        "surface-container-low": "#f4f2ff",
        "surface-container": "#edecff",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "on-primary-fixed": "#181a2e",
        "surface-bright": "#fbf8ff",
        "surface": "#fbf8ff",
        "primary": "#16182c",
        "on-primary": "#ffffff",
        "surface-dim": "#d7d8f4",
        "on-surface-variant": "#46464d",
        "on-secondary-container": "#5b2100",
        "on-primary-fixed-variant": "#43455b",
        "on-background": "#181a2e",
        "secondary": "#a14000",
        "on-primary-container": "#9394ae",
        "on-secondary-fixed": "#351000",
        "inverse-primary": "#c4c4df",
      },
      fontFamily: {
        "headline": ["Space Grotesk"],
        "body": ["Inter"],
        "label": ["Space Grotesk"],
      },
    },
  },
  plugins: [],
}
